default: &default
  adapter: postgresql
  encoding: unicode
  username: 'postgres'
  password: 'password'
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: pictagram_development

test:
  <<: *default
  database: pictagram_test

production:
  <<: *default
  database: pictagram_production